// Generated by build script, do not edit!
#ifndef RC_INVOKED
#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/buildslave/unity/build";

    extern const char* const UnityVersion = "2021.2.12f1";
    extern const char* const UnityVersionDigits = "2021.2.12";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 12;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.2.12f1_48b1aa000234";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.2.12f1_48b1aa000234";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.2.12f1 (48b1aa000234)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 4764074;

    extern const UInt64 UnityVersionDate = 1644334534;
    extern const char* const UnityVersionBranch = "2021.2/staging";
    extern const char* const UnityVersionDisplay = "2021.2.12f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.2.12f1.4383";
    extern const char* const UnityVersionRevision = "48b1aa000234";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.2.12f1 (48b1aa000234)";
    extern const wchar_t* const L_UnityVersion = L"2021.2.12f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 12
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.2.12f1_48b1aa000234"
    #define UNITY_VERSION_PARENS_HASH "2021.2.12f1 (48b1aa000234)"
    #define UNITY_VERSION_BLD 4764074
    #define UNITY_VERSION_WIN "2021.2.12.4764074"

#endif // !RC_INVOKED
